name: Deploy Digital Garden
on:
  push:
    branches: [ "main" ]  # Ändere zu deinem Standard-Branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "src/site"  # Pfad zu deinen veröffentlichten Notizen (z. B. "./docs" oder "./src/site")
      - uses: actions/deploy-pages@v2
